// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodefs = require("node:fs");
var Tokenizer = require("./tokenizer.bs.js");
var HtmlOutput = require("./htmlOutput.bs.js");
var Core__Array = require("@rescript/core/src/Core__Array.bs.js");
var Core__Option = require("@rescript/core/src/Core__Option.bs.js");
var Core__Promise = require("@rescript/core/src/Core__Promise.bs.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

function loadSample() {
  return Nodefs.readFileSync("sample.arcd", {
                encoding: "utf8"
              }).toString();
}

var EndOfFile = /* @__PURE__ */Caml_exceptions.create("Arcadam.EndOfFile");

var lines = loadSample().split("\n");

async function nextLine(lnum, codeIndent) {
  var line = lines[lnum];
  if (line !== undefined) {
    var count = Tokenizer.countSpaces(line);
    var codeIndent$1 = count > 0 || line.length === 0 ? codeIndent : ">.".indexOf(line.charAt(0)) === -1;
    return [
            line.trim(),
            lnum + 1 | 0,
            codeIndent$1,
            count
          ];
  }
  throw {
        RE_EXN_ID: EndOfFile,
        _1: "EOF",
        Error: new Error()
      };
}

function specialCharsStep(text) {
  var result = text.replaceAll(/&/g, "&amp;");
  var result$1 = result.replaceAll(/</g, "&lt;");
  return result$1.replaceAll(/>/g, "&gt;");
}

function parseAttribute(atext, attributes) {
  var pattern = "^\\s*([.]?[" + Tokenizer.alpha + "]([.]?[" + Tokenizer.alnum + "])*)";
  var attrExpr = new RegExp(pattern);
  var k = Tokenizer.getMatches(attrExpr, atext);
  if (k.length !== 2) {
    console.log("Failed to parse:", k);
    return ;
  }
  var name = k[0];
  console.log("Parse: attribute", name);
  attributes.set(name, "");
}

function parseMarker(atext) {
  var pattern = "^\\s*([!-@\[-" + Tokenizer.backtick + "|~])\\s*(.*)";
  var markerExpr = new RegExp(pattern);
  var match = Tokenizer.getMatches(markerExpr, atext);
  if (match.length !== 2) {
    console.log("Failed to parse:", atext);
    return ;
  }
  var symbol = match[0];
  var args = match[1];
  console.log("Parse: marker prefix:", symbol, "rest:", args);
}

function doOutput(tokens, Output) {
  Core__Option.forEach(tokens, (function (token) {
          if (typeof token !== "object") {
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "arcadam.res",
                    74,
                    11
                  ],
                  Error: new Error()
                };
          }
          switch (token.TAG) {
            case "Text" :
                Output.outputText(token._0);
                return Output.endText();
            case "Marker" :
                return parseMarker(token._0);
            default:
              throw {
                    RE_EXN_ID: "Assert_failure",
                    _1: [
                      "arcadam.res",
                      74,
                      11
                    ],
                    Error: new Error()
                  };
          }
        }));
}

function parseDocument(tok, Output) {
  var _attributes = new Map();
  var _replacements = new Map();
  var $$final = Core__Array.reduce(tok, undefined, (function (acc, token) {
          var exit = 0;
          if (typeof token !== "object") {
            exit = 1;
          } else {
            switch (token.TAG) {
              case "Text" :
                  var value = token._0;
                  if (acc !== undefined) {
                    if (typeof acc !== "object") {
                      throw {
                            RE_EXN_ID: "Assert_failure",
                            _1: [
                              "arcadam.res",
                              102,
                              19
                            ],
                            Error: new Error()
                          };
                    }
                    switch (acc.TAG) {
                      case "Text" :
                          Output.outputText(acc._0);
                          return token;
                      case "Heading" :
                          Output.outputHeading(acc._0, value);
                          return ;
                      case "Marker" :
                          parseMarker(acc._0);
                          return token;
                      case "ReplacementKey" :
                          _replacements.set(acc._0, value);
                          return ;
                      case "Hyperlink" :
                          Output.outputHyperlink(acc._0, value);
                          return {
                                  TAG: "Text",
                                  _0: ""
                                };
                      default:
                        throw {
                              RE_EXN_ID: "Assert_failure",
                              _1: [
                                "arcadam.res",
                                102,
                                19
                              ],
                              Error: new Error()
                            };
                    }
                  } else {
                    Output.startText();
                    return token;
                  }
              case "Spaces" :
                  return acc;
              case "Marker" :
              case "Hyperlink" :
                  exit = 2;
                  break;
              default:
                exit = 1;
            }
          }
          switch (exit) {
            case 1 :
                doOutput(acc, Output);
                if (typeof token !== "object") {
                  return ;
                }
                switch (token.TAG) {
                  case "Attribute" :
                      parseAttribute(token._0, _attributes);
                      return ;
                  case "Heading" :
                  case "ReplacementKey" :
                      return token;
                  default:
                    return ;
                }
            case 2 :
                if (acc !== undefined) {
                  if (typeof acc !== "object") {
                    throw {
                          RE_EXN_ID: "Assert_failure",
                          _1: [
                            "arcadam.res",
                            113,
                            13
                          ],
                          Error: new Error()
                        };
                  }
                  switch (acc.TAG) {
                    case "Text" :
                        Output.outputText(acc._0);
                        break;
                    case "Marker" :
                        parseMarker(acc._0);
                        break;
                    default:
                      throw {
                            RE_EXN_ID: "Assert_failure",
                            _1: [
                              "arcadam.res",
                              113,
                              13
                            ],
                            Error: new Error()
                          };
                  }
                } else {
                  Output.startText();
                }
                return token;
            
          }
        }));
  doOutput($$final, Output);
  _replacements.forEach(function (value, name) {
        console.log("Key:", name, "Value:", value);
      });
}

var Success = /* @__PURE__ */Caml_exceptions.create("Arcadam.Success");

function nextTokens(lnum, codeIndent, tok) {
  return nextLine(lnum, codeIndent).then(function (param) {
              return Promise.resolve([
                          param[0],
                          param[1],
                          param[2],
                          param[3],
                          tok
                        ]);
            });
}

function promi(param) {
  var lnum = param[2];
  var ltype = param[1];
  var tok = param[0];
  var tmp;
  if (typeof ltype !== "object") {
    tmp = nextTokens(lnum, true, tok).then(Tokenizer.consumeIndentedCode);
  } else {
    switch (ltype.TAG) {
      case "Initial" :
          tmp = nextTokens(lnum, ltype._0, tok).then(Tokenizer.consumeInitialLine);
          break;
      case "Following" :
          tmp = nextTokens(lnum, ltype._0, tok).then(Tokenizer.consumeLine);
          break;
      case "Code" :
          tmp = nextTokens(lnum, ltype._0, tok).then(Tokenizer.consumeCodeLine);
          break;
      case "List" :
          tmp = nextTokens(lnum, ltype._0, tok).then(Tokenizer.consumeListLine);
          break;
      
    }
  }
  return Core__Promise.$$catch(tmp.then(promi), (function (err) {
                if (err.RE_EXN_ID === EndOfFile) {
                  tok.forEach(function (token) {
                        console.log("T: ", token);
                      });
                  console.log("DONE " + String(tok.length));
                  parseDocument(tok, {
                        outputHeading: HtmlOutput.outputHeading,
                        outputHyperlink: HtmlOutput.outputHyperlink,
                        startText: HtmlOutput.startText,
                        outputText: HtmlOutput.outputText,
                        endText: HtmlOutput.endText
                      });
                  return Promise.resolve();
                } else {
                  console.log("Unexpected error");
                  return Promise.resolve();
                }
              }));
}

promi([
      [],
      {
        TAG: "Initial",
        _0: true
      },
      0
    ]);

var outputFormat = "Html";

var subs = /* [] */0;

var attrs = "";

var lnum = 0;

exports.loadSample = loadSample;
exports.EndOfFile = EndOfFile;
exports.lines = lines;
exports.nextLine = nextLine;
exports.outputFormat = outputFormat;
exports.specialCharsStep = specialCharsStep;
exports.parseAttribute = parseAttribute;
exports.parseMarker = parseMarker;
exports.doOutput = doOutput;
exports.parseDocument = parseDocument;
exports.subs = subs;
exports.attrs = attrs;
exports.lnum = lnum;
exports.Success = Success;
exports.nextTokens = nextTokens;
exports.promi = promi;
/* lines Not a pure module */
