// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function outputHyperlink(link, text) {
  console.log("<a href=\"" + link + "\">" + text + "</a>");
}

function startText() {
  console.log("<div>");
}

function endText() {
  console.log("</div>");
}

function outputText(text) {
  console.log(text);
}

function outputHeading(level, text) {
  console.log("<h" + level.toString() + ">" + text + "</h" + level.toString() + ">");
}

exports.outputHyperlink = outputHyperlink;
exports.startText = startText;
exports.endText = endText;
exports.outputText = outputText;
exports.outputHeading = outputHeading;
/* No side effect */
