// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var alpha = "A-Za-z";

var alnum = "0-9" + alpha;

function getMatches(regex, someline) {
  var result = regex.exec(someline);
  if (result == null) {
    return [];
  } else {
    return result.slice(1).map(function (opt) {
                if (opt !== undefined) {
                  return opt;
                } else {
                  return "";
                }
              });
  }
}

function countSpaces(line) {
  var initialSpaces = /^([ \t]+)/;
  var match = getMatches(initialSpaces, line);
  if (match.length !== 1) {
    return 0;
  }
  var spaces = match[0];
  var count = 0;
  for(var i = 0 ,i_finish = spaces.length; i < i_finish; ++i){
    var c = spaces.charAt(i);
    switch (c) {
      case " " :
          count = count + 1 | 0;
          break;
      case "\t" :
          count = ((count / 4 | 0) << 2) + 4 | 0;
          break;
      default:
        console.error("unreachable");
    }
  }
  return count;
}

function consumeIndentSigns(line) {
  var indentSign = /^((>\s*)*>\s+)/;
  var match = getMatches(indentSign, line);
  if (match.length !== 2) {
    return [];
  }
  var indent = match[0];
  var onlySigns = indent.replaceAll(/\s+/g, "");
  return [{
            TAG: "IndentSigns",
            _0: onlySigns.length,
            _1: indent.length
          }];
}

function consumeBlockTitle(line) {
  var blockTitleLine = /^=\s+(.*)$/;
  var match = getMatches(blockTitleLine, line);
  if (match.length !== 1) {
    return [];
  }
  var title = match[0];
  return [{
            TAG: "BlockTitle",
            _0: title
          }];
}

function consumeHeading(line) {
  var headingLine = /^(#+)\s+([^\s].*)$/;
  var match = getMatches(headingLine, line);
  if (match.length !== 2) {
    return [];
  }
  var signs = match[0];
  var title = match[1];
  var level = signs.length;
  return [
          {
            TAG: "Heading",
            _0: level
          },
          {
            TAG: "Text",
            _0: title
          }
        ];
}

function consumeReplacement(line) {
  var pattern = "^:key:([" + alpha + "][_" + alnum + "]*(\\.[_" + alnum + "]+)*)\\s+(.*)\$";
  var substLine = new RegExp(pattern);
  var match = getMatches(substLine, line);
  if (match.length !== 3) {
    return [];
  }
  var name = match[0];
  var value = match[2];
  return [
          {
            TAG: "ReplacementKey",
            _0: name
          },
          {
            TAG: "Text",
            _0: value
          }
        ];
}

function consumeAttribute(line) {
  var attrLine = /^\[\s*([^\[\]]*)\]\s*$/;
  var match = getMatches(attrLine, line);
  if (match.length !== 1) {
    return [];
  }
  var attributes = match[0];
  return [{
            TAG: "Attribute",
            _0: attributes
          }];
}

function consumeInlineControl(line) {
  var controlLine = /\[\s*\?\s*([^ \]]*)(\s+[^\]]+)?\s*\]\((.*)\)/;
  var match = getMatches(controlLine, line);
  if (match.length !== 3) {
    return [];
  }
  var controlType = match[0];
  var params = match[1];
  var options = match[2];
  if (options === "") {
    return [{
              TAG: "InlineControl",
              _0: controlType,
              _1: params
            }];
  } else {
    return [
            {
              TAG: "InlineControl",
              _0: controlType,
              _1: params
            },
            {
              TAG: "ControlOptions",
              _0: options
            }
          ];
  }
}

function consumeStandaloneControl(line) {
  var controlLine = /^\[\s*!\s*([^ \]]*)(\s+[^\]]+)?\s*\](\((.*)\))?\s*$/;
  var match = getMatches(controlLine, line);
  if (match.length !== 4) {
    return [];
  }
  var controlType = match[0];
  var params = match[1];
  var options = match[3];
  if (options === "") {
    return [{
              TAG: "StandaloneControl",
              _0: controlType,
              _1: params
            }];
  } else {
    return [
            {
              TAG: "StandaloneControl",
              _0: controlType,
              _1: params
            },
            {
              TAG: "ControlOptions",
              _0: options
            }
          ];
  }
}

function consumeHyperlink(line) {
  var hlinkLine = /\[\s*([^\]]*)\]\(\s*([^\s\)]*)\s*\)/;
  var match = getMatches(hlinkLine, line);
  if (match.length !== 2) {
    return [];
  }
  var text = match[0];
  var link = match[1];
  return [
          {
            TAG: "Hyperlink",
            _0: link
          },
          {
            TAG: "Text",
            _0: text
          }
        ];
}

function consumeMarker(line) {
  var markerLine = /^\[\s*([^\]]+)\]:\s*$/;
  var match = getMatches(markerLine, line);
  if (match.length !== 1) {
    return [];
  }
  var marker = match[0];
  return [{
            TAG: "Marker",
            _0: marker
          }];
}

function consumeBulletListItem(line) {
  var itemLine = /^([*]+)\s+(.*)$/;
  var match = getMatches(itemLine, line);
  if (match.length !== 2) {
    return [];
  }
  var stars = match[0];
  var text = match[1];
  var level = stars.length;
  return [
          {
            TAG: "BulletListItem",
            _0: level
          },
          {
            TAG: "Text",
            _0: text
          }
        ];
}

function consumeNumberedListItem(line) {
  var itemLine = /^1?([.]+)\s+(.*)$/;
  var match = getMatches(itemLine, line);
  if (match.length !== 2) {
    return [];
  }
  var dots = match[0];
  var text = match[1];
  var level = dots.length;
  return [
          {
            TAG: "NumberedListItem",
            _0: level
          },
          {
            TAG: "Text",
            _0: text
          }
        ];
}

function consumeNestingSigns(line) {
  var itemLine = /^([.]+)\s*$/;
  var match = getMatches(itemLine, line);
  if (match.length !== 1) {
    return [];
  }
  var dots = match[0];
  var level = dots.length;
  return [{
            TAG: "Nesting",
            _0: level
          }];
}

function consumeBlockDelimiter(line) {
  switch (line) {
    case "" :
        return ["Empty"];
    case "****" :
        return ["SidebarBlockDelimiter"];
    case "--" :
        return ["FreeBlockDelimiter"];
    case "====" :
        return ["ExampleBlockDelimiter"];
    case "___" :
        return ["QuoteBlockDelimiter"];
    case "```" :
        return ["CodeBlockDelimiter"];
    case "~~~~" :
        return ["ContentBlockDelimiter"];
    default:
      return [];
  }
}

function consumeRegularLine(line) {
  var tokens = consumeBlockDelimiter(line);
  if (tokens.length !== 1) {
    var chara = line.charAt(0);
    var tok;
    switch (chara) {
      case "*" :
          tok = consumeBulletListItem(line);
          break;
      case "." :
      case "1" :
          tok = consumeNumberedListItem(line);
          break;
      case "[" :
          var tokens$1 = consumeMarker(line);
          if (Caml_obj.notequal(tokens$1, [])) {
            tok = tokens$1;
          } else {
            var tokens$2 = consumeStandaloneControl(line);
            if (Caml_obj.notequal(tokens$2, [])) {
              tok = tokens$2;
            } else {
              var tokens$3 = consumeInlineControl(line);
              tok = Caml_obj.notequal(tokens$3, []) ? tokens$3 : consumeHyperlink(line);
            }
          }
          break;
      default:
        tok = [];
    }
    if (Caml_obj.equal(tok, [])) {
      return [{
                TAG: "Text",
                _0: line
              }];
    } else {
      return tok;
    }
  }
  var match = tokens[0];
  if (typeof match !== "object" && match === "CodeBlockDelimiter") {
    return [{
              TAG: "Text",
              _0: line
            }];
  } else {
    return tokens;
  }
}

function tokeniseLine(line, tok, lnum, codeIndent) {
  if (line === "") {
    return Promise.resolve([
                tok.concat(["Empty"]),
                {
                  TAG: "Initial",
                  _0: codeIndent
                },
                lnum
              ]);
  }
  var chara = line.charAt(0);
  var tokens;
  switch (chara) {
    case "." :
        tokens = consumeNestingSigns(line);
        break;
    case ">" :
        var indents = consumeIndentSigns(line);
        if (indents.length !== 1) {
          tokens = [];
        } else {
          var match = indents[0];
          if (typeof match !== "object") {
            tokens = [];
          } else if (match.TAG === "IndentSigns") {
            var rest = line.slice(match._1);
            tokens = indents.concat(consumeRegularLine(rest));
          } else {
            tokens = [];
          }
        }
        break;
    default:
      tokens = [];
  }
  var len = tokens.length;
  if (len < 3) {
    switch (len) {
      case 0 :
          var tokens$1 = consumeRegularLine(line);
          return Promise.resolve([
                      tok.concat(tokens$1),
                      {
                        TAG: "Following",
                        _0: codeIndent
                      },
                      lnum
                    ]);
      case 1 :
          break;
      case 2 :
          var match$1 = tokens[0];
          var exit = 0;
          if (typeof match$1 === "object") {
            switch (match$1.TAG) {
              case "BulletListItem" :
              case "NumberedListItem" :
                  exit = 2;
                  break;
              default:
                
            }
          }
          if (exit === 2) {
            return Promise.resolve([
                        tok.concat(tokens),
                        {
                          TAG: "List",
                          _0: codeIndent
                        },
                        lnum
                      ]);
          }
          break;
      
    }
  }
  return Promise.resolve([
              tok.concat(tokens),
              {
                TAG: "Following",
                _0: codeIndent
              },
              lnum
            ]);
}

function consumeLineFactory(tokeniser) {
  return function (param) {
    var tok = param[4];
    var nspaces = param[3];
    var codeIndent = param[2];
    var lnum = param[1];
    var line = param[0];
    if (nspaces <= 0) {
      return tokeniser(line, tok, lnum, codeIndent);
    }
    if (codeIndent) {
      var tokens = [
        {
          TAG: "Spaces",
          _0: nspaces
        },
        {
          TAG: "IndentedCode",
          _0: line
        }
      ];
      return Promise.resolve([
                  tok.concat(tokens),
                  "Indented",
                  lnum
                ]);
    }
    var tok$1 = nspaces > 0 ? tok.concat([{
              TAG: "Spaces",
              _0: nspaces
            }]) : tok;
    return tokeniser(line, tok$1, lnum, codeIndent);
  };
}

var consumeLine = consumeLineFactory(tokeniseLine);

var EndOfBlock = /* @__PURE__ */Caml_exceptions.create("Tokenizer.EndOfBlock");

function tokeniseInitialLine(_line, _tok, lnum, _codeIndent) {
  while(true) {
    var codeIndent = _codeIndent;
    var tok = _tok;
    var line = _line;
    var tokens = consumeBlockDelimiter(line);
    if (tokens.length !== 1) {
      var chara = line.charAt(0);
      switch (chara) {
        case "#" :
            var tokens$1 = consumeHeading(line);
            if (Caml_obj.notequal(tokens$1, [])) {
              return Promise.resolve([
                          tok.concat(tokens$1),
                          {
                            TAG: "Following",
                            _0: codeIndent
                          },
                          lnum
                        ]);
            }
            var tokens$2 = consumeRegularLine(line);
            return Promise.resolve([
                        tok.concat(tokens$2),
                        {
                          TAG: "Following",
                          _0: codeIndent
                        },
                        lnum
                      ]);
        case ":" :
            var tokens$3 = consumeReplacement(line);
            if (tokens$3.length === 2) {
              var _name = tokens$3[0];
              if (typeof _name === "object" && _name.TAG === "ReplacementKey") {
                var _value = tokens$3[1];
                if (typeof _value === "object" && _value.TAG === "Text") {
                  return Promise.resolve([
                              tok.concat(tokens$3),
                              {
                                TAG: "Initial",
                                _0: codeIndent
                              },
                              lnum
                            ]);
                }
                
              }
              
            }
            if (!Caml_obj.equal(tokens$3, [])) {
              throw {
                    RE_EXN_ID: "Assert_failure",
                    _1: [
                      "tokenizer.res",
                      314,
                      10
                    ],
                    Error: new Error()
                  };
            }
            return Promise.resolve([
                        consumeRegularLine(line),
                        {
                          TAG: "Following",
                          _0: codeIndent
                        },
                        lnum
                      ]);
        case "=" :
            var tokens$4 = consumeBlockTitle(line);
            if (tokens$4.length === 1) {
              var _title = tokens$4[0];
              if (typeof _title === "object" && _title.TAG === "BlockTitle") {
                return Promise.resolve([
                            tok.concat(tokens$4),
                            {
                              TAG: "Initial",
                              _0: codeIndent
                            },
                            lnum
                          ]);
              }
              
            }
            if (!Caml_obj.equal(tokens$4, [])) {
              throw {
                    RE_EXN_ID: "Assert_failure",
                    _1: [
                      "tokenizer.res",
                      295,
                      10
                    ],
                    Error: new Error()
                  };
            }
            var tokens$5 = consumeRegularLine(line);
            return Promise.resolve([
                        tok.concat(tokens$5),
                        {
                          TAG: "Following",
                          _0: codeIndent
                        },
                        lnum
                      ]);
        case ">" :
            var indents = consumeIndentSigns(line);
            if (indents.length === 1) {
              var match = indents[0];
              if (typeof match === "object" && match.TAG === "IndentSigns") {
                var rest = line.slice(match._1);
                _codeIndent = false;
                _tok = tok.concat(indents);
                _line = rest;
                continue ;
              }
              
            }
            return tokeniseLine(line, tok, lnum, codeIndent);
        case "[" :
            var tokens$6 = consumeAttribute(line);
            if (tokens$6.length === 1) {
              var _attributes = tokens$6[0];
              if (typeof _attributes === "object" && _attributes.TAG === "Attribute") {
                return Promise.resolve([
                            tok.concat(tokens$6),
                            {
                              TAG: "Initial",
                              _0: codeIndent
                            },
                            lnum
                          ]);
              }
              
            }
            if (!Caml_obj.equal(tokens$6, [])) {
              throw {
                    RE_EXN_ID: "Assert_failure",
                    _1: [
                      "tokenizer.res",
                      323,
                      10
                    ],
                    Error: new Error()
                  };
            }
            var tokens$7 = consumeMarker(line);
            if (Caml_obj.notequal(tokens$7, [])) {
              return Promise.resolve([
                          tok.concat(tokens$7),
                          {
                            TAG: "Initial",
                            _0: codeIndent
                          },
                          lnum
                        ]);
            }
            var tokens$8 = consumeRegularLine(line);
            return Promise.resolve([
                        tok.concat(tokens$8),
                        {
                          TAG: "Following",
                          _0: codeIndent
                        },
                        lnum
                      ]);
            break;
        default:
          return tokeniseLine(line, tok, lnum, codeIndent);
      }
    } else {
      var match$1 = tokens[0];
      if (typeof match$1 !== "object" && match$1 === "CodeBlockDelimiter") {
        return Promise.resolve([
                    tok.concat(tokens),
                    {
                      TAG: "Code",
                      _0: codeIndent
                    },
                    lnum
                  ]);
      }
      return Promise.resolve([
                  tok.concat(tokens),
                  {
                    TAG: "Initial",
                    _0: codeIndent
                  },
                  lnum
                ]);
    }
  };
}

var consumeInitialLine = consumeLineFactory(tokeniseInitialLine);

function consumeCodeLine(param) {
  var tok = param[4];
  var nspaces = param[3];
  var codeIndent = param[2];
  var lnum = param[1];
  var line = param[0];
  var tok$1 = nspaces > 0 ? tok.concat([{
            TAG: "Spaces",
            _0: nspaces
          }]) : tok;
  if (line === "```") {
    return Promise.resolve([
                tok$1.concat(["CodeBlockDelimiter"]),
                {
                  TAG: "Initial",
                  _0: codeIndent
                },
                lnum
              ]);
  } else {
    return Promise.resolve([
                tok$1.concat([{
                        TAG: "CodeText",
                        _0: line
                      }]),
                {
                  TAG: "Code",
                  _0: codeIndent
                },
                lnum
              ]);
  }
}

function consumeIndentedCode(param) {
  var tok = param[4];
  var nspaces = param[3];
  var lnum = param[1];
  var line = param[0];
  if (nspaces <= 0) {
    return tokeniseInitialLine(line, tok, lnum, param[2]);
  }
  var tokens = [
    {
      TAG: "Spaces",
      _0: nspaces
    },
    {
      TAG: "IndentedCode",
      _0: line
    }
  ];
  return Promise.resolve([
              tok.concat(tokens),
              "Indented",
              lnum
            ]);
}

function consumeListLine(param) {
  var tok = param[4];
  var nspaces = param[3];
  var codeIndent = param[2];
  var lnum = param[1];
  var line = param[0];
  if (line === "") {
    return tokeniseInitialLine(line, tok, lnum, codeIndent);
  }
  var tok$1 = nspaces > 0 ? tok.concat([{
            TAG: "Spaces",
            _0: nspaces
          }]) : tok;
  var tokens = consumeBulletListItem(line);
  if (!Caml_obj.equal(tokens, [])) {
    return Promise.resolve([
                tok$1.concat(tokens),
                {
                  TAG: "List",
                  _0: codeIndent
                },
                lnum
              ]);
  }
  var tokens$1 = consumeNumberedListItem(line);
  if (Caml_obj.equal(tokens$1, [])) {
    return Promise.resolve([
                tok$1.concat([{
                        TAG: "Text",
                        _0: line
                      }]),
                {
                  TAG: "List",
                  _0: codeIndent
                },
                lnum
              ]);
  } else {
    return Promise.resolve([
                tok$1.concat(tokens$1),
                {
                  TAG: "List",
                  _0: codeIndent
                },
                lnum
              ]);
  }
}

var backtick = "`";

var tablen = 4;

exports.alpha = alpha;
exports.alnum = alnum;
exports.backtick = backtick;
exports.tablen = tablen;
exports.getMatches = getMatches;
exports.countSpaces = countSpaces;
exports.consumeIndentSigns = consumeIndentSigns;
exports.consumeBlockTitle = consumeBlockTitle;
exports.consumeHeading = consumeHeading;
exports.consumeReplacement = consumeReplacement;
exports.consumeAttribute = consumeAttribute;
exports.consumeInlineControl = consumeInlineControl;
exports.consumeStandaloneControl = consumeStandaloneControl;
exports.consumeHyperlink = consumeHyperlink;
exports.consumeMarker = consumeMarker;
exports.consumeBulletListItem = consumeBulletListItem;
exports.consumeNumberedListItem = consumeNumberedListItem;
exports.consumeNestingSigns = consumeNestingSigns;
exports.consumeBlockDelimiter = consumeBlockDelimiter;
exports.consumeRegularLine = consumeRegularLine;
exports.tokeniseLine = tokeniseLine;
exports.consumeLineFactory = consumeLineFactory;
exports.consumeLine = consumeLine;
exports.EndOfBlock = EndOfBlock;
exports.tokeniseInitialLine = tokeniseInitialLine;
exports.consumeInitialLine = consumeInitialLine;
exports.consumeCodeLine = consumeCodeLine;
exports.consumeIndentedCode = consumeIndentedCode;
exports.consumeListLine = consumeListLine;
/* consumeLine Not a pure module */
